name: Python CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Run Flake8
      run: poetry run flake8

    - name: Run tests and generate coverage report
      run: |
        poetry run coverage run -m pytest
        poetry run coverage xml

    - name: Upload coverage report
      uses: codecov/codecov-action@v2
      with:
        file: coverage.xml

