name: Python CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.13'  # Replace with your desired Python version

    - name: Install dependencies
      run: |
        pip install poetry
        cd refactorNCI  # Navigate to the refactorNCI directory
        poetry install
        
    - name: Lint with Flake8
      run: cd refactorNCI && poetry run flake8 || true

    - name: Install pytest
      run: poetry add --dev pytest pytest-cov
      working-directory: ${{ github.workspace }}/refactorNCI

    - name: Test with coverage
      run: |
        poetry run pytest --cov=pyproject.toml
        poetry add --dev coverage
        poetry run coverage run -m pytest 
        poetry run coverage report
      working-directory: ${{ github.workspace }}/refactorNCI
    - name: Coverage


    - name: Upload coverage report
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}  # Make sure to set up CODECOV_TOKEN in your repository secrets

