name: Python CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.13'  # Replace with your desired Python version

    - name: Install dependencies
      run: |
        pip install poetry
        cd refactorNCI  # Navigate to the refactorNCI directory
        poetry install
        
    - name: Lint with Flake8
      run: cd refactorNCI && poetry run flake8 || true

    - name: Install pytest
      run: 
        cd refactorNCI
        poetry add --dev pytest pytest-cov

    - name: Test with coverage
      run: |
        cd refactorNCI && poetry run coverage run -m pytest
        cd refactorNCI && poetry run coverage report -m

    - name: Upload coverage report
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}  # Make sure to set up CODECOV_TOKEN in your repository secrets

