name: Python CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.13'  # Replace with your desired Python version

    - name: Install dependencies
      run: |
        pip install poetry
        cd refactorNCI  # Navigate to the refactorNCI directory
        poetry install
        
    - name: Lint with Flake8
      run: cd refactorNCI && poetry run flake8 || true

    - name: Install pytest
      run: poetry add --dev pytest pytest-cov
      working-directory: ${{ github.workspace }}/refactorNCI

    - name: Test with coverage
      run: |
        poetry run pytest --cov=pyproject.toml
      working-directory: ${{ github.workspace }}/refactorNCI

    - name: Generate HTML Code Coverage Report
      run: |
        if [ -f .coverage ]; then
          poetry run coverage html
        else
          echo "No coverage data to report"
        fi
      working-directory: ${{ github.workspace }}/refactorNCI
      continue-on-error: true  # This step will continue even if it fails

    - name: Upload HTML Code Coverage Report
      if: always()  # This step will run even if the previous step fails
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage
        path: ${{ github.workspace }}/refactorNCI
      
    - name: Upload coverage reports to Codecov
      if: always()
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        
    


